language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=kinto-master
    - TOX_ENV=flake8
matrix:
  include:
    - env:
        - TOX_ENV=functional
      install:
        - make install install-kinto
        - make run-kinto &
    - env:
        - TOX_ENV=functional
          WITH=kinto-master
      install:
        - make install
        - pip install -U https://github.com/Kinto/kinto/zipball/master
        - make run-kinto &
  allow_failures:
    - env:
        - TOX_ENV=functional
        - TOX_ENV=functional
          WITH=kinto-master
install:
    - make install
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
