language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=kinto-master
    - TOX_ENV=functional
    - TOX_ENV=flake8
matrix:
  allow_failures:
    - env: TOX_ENV=functional
install:
    - make install
script:
    - tox -e $TOX_ENV
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
